### ISSUE TITLE
Consider moving AppVeyor downloads back to curl

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#110]
We currently have a bit of a hack to get AppVeyor downloads working

```yml
  - ps: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
  - ps: Start-FileDownload https://win.rustup.rs -FileName rustup-init.exe
  ...
```

When I originally created the AppVeyor script I thought that `Start-FileDownload` was some kind of built in Powershell thing, but it's really an AppVeyor specific thing so I think it would be better to just use standard `curl`.
