### ISSUE TITLE
Update Piston dependencies

### ISSUE THREAD

**Issue by johnthagen** [johnthagen/rust-belt#193]
The following dependencies are out of date and need updated, but cause build failures and require refactoring:

```toml
piston_window = "0.105.0"
piston2d-opengl_graphics = "0.69.0"
piston2d-sprite = "0.58.0"
piston-ai_behavior = "0.31.0"
```
